# =========================================================
# SMART ASSESS AI - APPLICATION CONFIGURATION
# =========================================================

# Server
server.port=8080


# =========================================================
# MYSQL DATABASE
# =========================================================


spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# =========================================================
# JWT SECURITY
# =========================================================

app.jwt.secret=c21hcnRhcnQ3NGl1c3RyaW5nZm9yU21hcnRBc3Nlc3NBcHA=
app.jwt.expiration-ms=86400000


# =========================================================
# GOOGLE GEMINI AI
# =========================================================

app.ai.api-key=${GEMINI_API_KEY}
app.ai.gemini-url=app.ai.gemini-url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent


# =========================================================
# STATIC RESOURCES
# =========================================================

spring.web.resources.static-locations=classpath:/static/


# =========================================================
# FILE UPLOAD
# =========================================================

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB